//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FangMomFucker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FangMomFucker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 103.16.207.1/24
        ///103.28.94.1/24
        ///110.164.10.1/24
        ///110.164.4.1/24
        ///110.164.8.1/24
        ///114.108.207.1/24
        ///115.84.108.1/24
        ///119.110.118.1/24
        ///183.91.18.1/24
        ///202.78.113.1/24
        ///209.85.145.1/24
        ///209.85.147.1/24
        /// 的本地化字符串。
        /// </summary>
        internal static string GWS {
            get {
                return ResourceManager.GetString("GWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.255.22.1/24
        ///1.255.33.1/24
        ///1.9.131.1/24
        ///1.9.22.1/24
        ///1.9.24.1/24
        ///1.9.57.1/24
        ///101.0.38.1/24
        ///101.78.13.1/24
        ///103.1.139.1/24
        ///103.13.116.1/24
        ///103.13.250.1/24
        ///103.15.61.1/24
        ///103.16.204.1/24
        ///103.16.205.1/24
        ///103.16.207.1/24
        ///103.18.67.1/24
        ///103.2.116.1/24
        ///103.2.118.1/24
        ///103.241.59.1/24
        ///103.249.65.1/24
        ///103.25.229.1/24
        ///103.28.94.1/24
        ///103.30.113.1/24
        ///103.31.46.1/24
        ///103.7.200.1/24
        ///106.103.1.1/24
        ///106.103.2.1/24
        ///106.162.199.1/24
        ///106.162.200.1/24
        ///110.163.42.1/24
        ///110.164.10.1/24
        ///110.164.12.1/24 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 自带好ip {
            get {
                return ResourceManager.GetString("自带好ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 113.21.241.1/24
        ///173.194.11.1/24
        ///173.194.12.1/24
        ///173.194.130.1/24
        ///173.194.131.1/24
        ///173.194.132.1/24
        ///173.194.134.1/24
        ///173.194.137.1/24
        ///173.194.138.1/24
        ///173.194.139.1/24
        ///173.194.14.1/24
        ///173.194.140.1/24
        ///173.194.141.1/24
        ///173.194.142.1/24
        ///173.194.144.1/24
        ///173.194.147.1/24
        ///173.194.15.1/24
        ///173.194.152.1/24
        ///173.194.154.1/24
        ///173.194.16.1/24
        ///173.194.17.1/24
        ///173.194.2.1/24
        ///173.194.200.1/24
        ///173.194.201.1/24
        ///173.194.21.1/24
        ///173.194.218.1/24
        ///173.194.22.1/24
        ///173.194.28.1/24
        ///173.194.29.1/24
        ///173 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 谷歌官方 {
            get {
                return ResourceManager.GetString("谷歌官方", resourceCulture);
            }
        }
    }
}
